export { default as AmtInput } from './AmtInput';
export { default as City } from './City';
export { default as DoublePwd } from './DoublePwd';
export { default as Email } from './Email';
export { default as MobilePhone } from './MobilePhone';
export { default as Name } from './Name';
export { default as NumberCard } from './NumberCard';
export { default as Sex } from './Sex';
export { default as UserId } from './UserId';
